export enum RFQStatus {
  PREPARING = 'PREPARING',
  SENT = 'SENT',
  RESPONSE_PENDING = 'RESPONSE_PENDING',
  RESPONSE_RECEIVED = 'RESPONSE_RECEIVED',
  REVIEWED = 'REVIEWED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
  CLOSED = 'CLOSED',
}
